version: '3.8'

services:
  backend:
    build: ./BACKEND
    container_name: backend-container
    env_file:
      - ./BACKEND/.env
    ports:
      - "3001:3001"
    volumes:
      - ./BACKEND/dev.db:/app/dev.db
      - ./BACKEND/prisma:/app/prisma
    restart: unless-stopped

  frontend:
    build: ./FRONTEND
    container_name: frontend-container
    ports:
      - "80:80" # Открыт только один порт для всего!
    depends_on:
      - backend
    restart: unless-stopped
